baseURL: "https://andergisomon.github.io/"
title: Volintine Ander, Zechariah Hwong, Kensley Kudang, Aziz Abdul Bagas, Eddry Haqimy Yusri
paginate: 5
theme: papermod

# module:
#   imports:
#     - path: github.com/hugomods/images

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: EFB2073 Project Report
  description: "Project Report for EFB2073"
  keywords: [Blog, Portfolio, PaperMod]
  author: ["Volintine Ander", "Zechariah Hwong", "Kensley Kudang", "Aziz Abdul Bagas", "Eddry Haqimy Yusri"]
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  hideauthor: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "EFB2073 Project Report"
    icon: 
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "IoT Control Module with RISC-V"
    Subtitle: "using NO Arduino code"
    Content: "(Intra)net of Things implemented using the ESP-NOW protocol with two ESP32C3 boards. A multipurpose wireless control module, implemented in **pure ESP IDF**."

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name: Search
      url: /search
      weight: 20
    - identifier: website_source
      name: Website source
      url: "https://github.com/andergisomon/efb2073_report"
      weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: monokai
  goldmark:
    parser:
      attribute:
        block: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
